# Generated by Django 3.2 on 2021-06-26 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Section_Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures_Gallery',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Selling_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selling_Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='userimages')),
                ('Email', models.EmailField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Address', models.TextField()),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Store_Timings', models.CharField(max_length=100)),
                ('Facebook', models.CharField(max_length=50)),
                ('Instagram', models.CharField(max_length=50)),
                ('Twitter', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('Product_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Product_Image1', models.ImageField(upload_to='img/%y')),
                ('Product_Image2', models.ImageField(upload_to='img/%y')),
                ('Product_Title', models.CharField(max_length=200)),
                ('Product_Description', models.TextField()),
                ('Product_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_category')),
                ('Product_Selling_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product_selling_category')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=5000)),
                ('Quantity', models.IntegerField(default=1)),
                ('Price', models.IntegerField()),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=11)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=50)),
                ('Province', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Zip_Code', models.CharField(max_length=50)),
                ('Date', models.DateField(default=datetime.datetime.today)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user_details')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
    ]
