# Generated by Django 3.2 on 2021-06-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='Product_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
