# Generated by Django 3.2 on 2021-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_details_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='Product_ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
