# Generated by Django 3.2 on 2021-06-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_details_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_request',
            name='Product',
            field=models.CharField(max_length=255),
        ),
    ]
