# Generated by Django 3.2 on 2021-06-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_request_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='userimages'),
        ),
    ]
