# Generated by Django 3.2 on 2021-06-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_user_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
