# Generated by Django 3.2 on 2021-06-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_user_details_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_request',
            name='Product',
        ),
        migrations.AddField(
            model_name='order_request',
            name='Product_Title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product_details'),
        ),
    ]
