# Generated by Django 3.2 on 2021-06-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210627_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_request',
            name='Product_Title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_details'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='userimages'),
        ),
    ]
