# Generated by Django 3.2 on 2021-06-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210627_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Image',
            field=models.ImageField(default='default.png', null=True, upload_to='userimages'),
        ),
    ]
