# Generated by Django 3.2 on 2021-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_user_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='userimages'),
        ),
    ]
