# Generated by Django 3.2 on 2021-07-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_user_details_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_info',
            name='Store_Name',
            field=models.CharField(default='Time Zone', max_length=255),
            preserve_default=False,
        ),
    ]
