# Generated by Django 3.2 on 2021-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_website_info_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_info',
            name='City',
            field=models.CharField(default='Lahore', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_info',
            name='Zip_Code',
            field=models.CharField(default=55360, max_length=50),
            preserve_default=False,
        ),
    ]
