# Generated by Django 3.2 on 2021-07-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orders_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Payment',
            new_name='Paid',
        ),
    ]
