# Generated by Django 3.2 on 2021-07-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
