# Generated by Django 3.2 on 2021-07-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_delete_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
