# Generated by Django 3.2 on 2021-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_user_details_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_request',
            name='Delivered',
            field=models.BooleanField(default=False),
        ),
    ]
